# Generated by Django 5.2 on 2025-05-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DFA', 'Deterministe'), ('NFA', 'Non Deterministe'), ('EFA', 'Epsilon-transitions')], default='DFA', max_length=3)),
                ('alphabet', models.CharField(help_text='Ex: a,b,c', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('est_initial', models.BooleanField(default=False)),
                ('est_final', models.BooleanField(default=False)),
                ('automate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='Automates.automate')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(help_text='Ex: a, b, ou ε', max_length=10)),
                ('automate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='Automates.automate')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_entrantes', to='Automates.etat')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_sortantes', to='Automates.etat')),
            ],
        ),
    ]
